services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .volume/:/var/lib/rabbitmq/
      - .volume/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    # networks:
    #   - mynet

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"

    # networks:
    #   - mynet
    depends_on:
      - rabbitmq
  
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: ./dockerfile
  #   networks:
  #     - mynet
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy


# networks:
#   mynet:
#     driver: bridge